---
apiVersion: pkg.crossplane.io/v1alpha1
kind: ControllerConfig
metadata:
  name: opentofu-config
  labels:
    app: crossplane-provider-opentofu
spec:
  args: ["-d"]
---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: crossplane-provider-opentofu
spec:
  package: xpkg.upbound.io/upbound/provider-opentofu:v0.2.2
  controllerConfigRef:
    name: opentofu-config
